import {
  FaBook,
  FaGlassCheers,
  FaHeart,
  FaHome,
  FaUmbrellaBeach,
  FaUsers,
} from 'react-icons/fa';

export const mockGroups = [
  {
    id: 'grp-001',
    name: 'Casal - Marina & João',
    members: ['Marina', 'João'],
    status: 'Você deve: R$ 47,50',
    statusColor: 'text-red-600',
    icon: <FaHeart className="text-pink-500" />,
    totalBalance: 1247.3,
    pendingDebts: [
      {
        id: 1,
        name: 'Marina',
        amount: 47.5,
        type: 'owesYou',
        to: 'João',
      },
    ],
    youOwe: [
      { id: 1, name: 'João', amount: 47.5, type: 'youOwe', to: 'Marina' },
    ],
    recentExpenses: [
      {
        id: 1,
        description: 'Jantar no Restaurante Italiano',
        amount: 47.5,
      },
      { id: 2, description: 'Cinema com pipoca', amount: 60.0 },
    ],
  },
  {
    id: 'grp-002',
    name: 'Família Silva',
    members: ['Pai', 'Mãe', 'Filho 1', 'Filha 1'],
    status: 'Você recebe: R$ 25,00',
    statusColor: 'text-green-600',
    icon: <FaUsers className="text-blue-600" />,
    totalBalance: 525.0,
    pendingDebts: [
      {
        id: 1,
        name: 'Filho 1',
        amount: 25.0,
        type: 'owesYou',
        to: 'Você',
      },
    ],
    youOwe: [],
    recentExpenses: [
      { id: 1, description: 'Mercado Semanal', amount: 320.0 },
      { id: 2, description: 'Passeio no Parque', amount: 80.0 },
    ],
  },
  {
    id: 'grp-003',
    name: 'Apartamento Compartilhado',
    members: ['Lucas', 'Ana', 'Pedro', 'Julia', 'Carlos'],
    status: 'Sem pendências',
    statusColor: 'text-gray-500',
    icon: <FaHome className="text-green-700" />,
    totalBalance: 0.0,
    pendingDebts: [],
    youOwe: [],
    recentExpenses: [
      { id: 1, description: 'Conta de Luz', amount: 150.0 },
      { id: 2, description: 'Internet Mensal', amount: 90.0 },
      { id: 3, description: 'Produtos de Limpeza', amount: 45.0 },
    ],
  },
  {
    id: 'grp-004',
    name: 'Viagem para Bahia',
    members: ['Você', 'Renata', 'Caio'],
    status: 'Você deve: R$ 120,00',
    statusColor: 'text-red-600',
    icon: <FaUmbrellaBeach className="text-yellow-600" />,
    totalBalance: 890.0,
    pendingDebts: [],
    youOwe: [
      {
        id: 1,
        name: 'Renata',
        amount: 120.0,
        type: 'youOwe',
        to: 'Renata',
      },
    ],
    recentExpenses: [
      { id: 1, description: 'Aluguel do Airbnb', amount: 600.0 },
      { id: 2, description: 'Almoço na Praia', amount: 90.0 },
    ],
  },
  {
    id: 'grp-005',
    name: 'Time da Faculdade',
    members: ['João', 'Beatriz', 'Você'],
    status: 'Você recebe: R$ 50,00',
    statusColor: 'text-green-600',
    icon: <FaBook className="text-purple-700" />,
    totalBalance: 50.0,
    pendingDebts: [
      { id: 1, name: 'João', amount: 25.0, type: 'owesYou', to: 'Você' },
      {
        id: 2,
        name: 'Beatriz',
        amount: 25.0,
        type: 'owesYou',
        to: 'Você',
      },
    ],
    youOwe: [],
    recentExpenses: [
      { id: 1, description: 'Impressão de Trabalho', amount: 50.0 },
    ],
  },
  {
    id: 'grp-006',
    name: 'Rolê de Sábado',
    members: ['Você', 'Vini', 'Letícia'],
    status: 'Sem pendências',
    statusColor: 'text-gray-500',
    icon: <FaGlassCheers className="text-pink-600" />,
    totalBalance: 210.0,
    pendingDebts: [],
    youOwe: [],
    recentExpenses: [
      { id: 1, description: 'Barzinho', amount: 120.0 },
      { id: 2, description: 'Uber', amount: 90.0 },
    ],
  },
];
