spring.application.name=notification-email

#e-mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MENSAGERIE_EMAIL}
spring.mail.password=${MENSAGERIE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2


# consumer application.properties
server.port=8081
spring.kafka.bootstrap-servers=localhost:9092

# consumer-specific settings
spring.kafka.consumer.group-id=${CONSUMER_GROUP_ID:finboostplus}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

# tópicos/variáveis
topic.message.consumer.signup.email=${ACCOUNT_REGISTRATION_TOPIC: default-topic}
topic.message.consumer.forgot.password.email=${FORGOT_PASSWORD_TOPIC: default-topic}
topic.message.consumer.expense.due.reminder.email=${EXPENSE_DUE_REMINDER_TOPIC: default-topic}
topic.api.consumer.group-id=${CONSUMER_GROUP_ID:finboostplus}

