name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install

      - name: Run Lint (frontend)
        run: |
          cd frontend
          npm run lint || echo "Lint warnings only"

      - name: Run Tests (frontend)
        run: |
          cd frontend
          npm run test -- --run --coverage || echo "No tests or tests failed (not blocking)"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: frontend/coverage
        continue-on-error: true

  backend:
    name: Backend (Spring Boot)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/finboostplus_teste/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Lint (backend - Checkstyle)
        run: |
          cd backend/finboostplus_teste
          mvn checkstyle:check || echo "Checkstyle warnings only"

      - name: Run Tests (backend)
        run: |
          cd backend/finboostplus_teste
          mvn test || echo "JUnit tests failed or not found (not blocking)"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: backend/finboostplus_teste/target/site/jacoco
        continue-on-error: true

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for better analysis

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/finboostplus_teste/pom.xml') }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
